py -m unittest -v
test_empty (test_ohe_unittest.TestOHE)
TypeError exception test ... ok
test_ohe01 (test_ohe_unittest.TestOHE) ... ok
test_ohe02 (test_ohe_unittest.TestOHE) ... ok
test_vect_size (test_ohe_unittest.TestOHE)
Vector size test ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.002s

OK